import { useMemo, useRef, useState } from "react";
import * as XLSX from "xlsx";
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, CartesianGrid, Legend, PieChart, Pie, Cell, LineChart, Line } from "recharts";

const STATUS_COLORS = { Active: "#34d399", Stored: "#fbbf24", Maintenance: "#fb923c", Repair: "#f87171", Retired: "#a78bfa", "Not yet delivered": "#60a5fa", Unknown: "#94a3b8" };
const PIE_COLORS = ["#38bdf8", "#34d399", "#a78bfa", "#fbbf24", "#f87171", "#fb923c", "#c084fc"];
const ENGINE_TYPE_COLORS = { CFM: "#38bdf8", LEAP: "#f97316" };
const MONTHS = { jan:1,january:1,feb:2,february:2,mar:3,march:3,apr:4,april:4,may:5,jun:6,june:6,jul:7,july:7,aug:8,august:8,sep:9,sept:9,september:9,oct:10,october:10,nov:11,november:11,dec:12,december:12 };

const card = (p = 16) => ({ background: "linear-gradient(145deg, rgba(23,34,54,0.75), rgba(11,19,32,0.8))", border: "1px solid rgba(148,163,184,0.2)", boxShadow: "0 10px 30px rgba(2,6,23,0.4)", borderRadius: 16, backdropFilter: "blur(10px)", padding: p });
const nHeader = (v) => String(v || "").trim().toLowerCase().replace(/[^a-z0-9]+/g, " ");
const num = (v) => { const n = Number(String(v ?? "").replace(/,/g, "").trim()); return Number.isFinite(n) ? n : 0; };
const text = (v, f = "Unknown") => String(v ?? "").trim() || f;
const monthSort = (v) => MONTHS[String(v || "").toLowerCase()] || MONTHS[String(v || "").toLowerCase().slice(0, 3)] || Number.MAX_SAFE_INTEGER;
const fmt = (v) => Math.round(v || 0).toLocaleString();

function pick(obj, keys) { for (const k of keys) if (obj[k] !== undefined && obj[k] !== null && obj[k] !== "") return obj[k]; return ""; }
function typeFrom(model) { return String(model || "").toUpperCase().includes("LEAP") ? "LEAP" : "CFM"; }
function familyFrom(model) { const m = String(model || "").toUpperCase(); if (m.includes("CFM56-3")) return "CFM56-3"; if (m.includes("CFM56-5")) return "CFM56-5"; if (m.includes("CFM56-7")) return "CFM56-7"; if (m.includes("LEAP-1A")) return "LEAP-1A"; if (m.includes("LEAP-1B")) return "LEAP-1B"; if (m.includes("LEAP-1C")) return "LEAP-1C"; if (m.includes("LEAP")) return "LEAP"; if (m.includes("CFM56")) return "CFM56"; return "Other"; }
function dashFrom(model) { const m = String(model || "").toUpperCase().match(/-(\d[A-Z]?)/); return m ? m[1] : "Unknown"; }
function statusFrom(v) { const s = String(v || "").trim(); const l = s.toLowerCase(); if (!s) return "Unknown"; if (l.includes("active")) return "Active"; if (l.includes("store")) return "Stored"; if (l.includes("maint")) return "Maintenance"; if (l.includes("repair")) return "Repair"; if (l.includes("retired")) return "Retired"; if (l.includes("not yet delivered")) return "Not yet delivered"; return s; }
function monthFrom(raw, file) { const d = String(raw || "").trim().toLowerCase(); if (MONTHS[d]) return d.slice(0,3).toUpperCase(); const f = String(file || "").toLowerCase(); const k = Object.keys(MONTHS).find((x) => f.includes(x)); return k ? k.slice(0,3).toUpperCase() : "Unknown"; }
function parseWorkbook(file, wb) { const sheet = wb.Sheets[wb.SheetNames[0]]; const rows = XLSX.utils.sheet_to_json(sheet, { defval: "" }); return rows.map((source, i) => { const x = {}; Object.entries(source).forEach(([k, v]) => { x[nHeader(k)] = v; }); const model = pick(x, ["engine full name", "engine model", "engine", "model"]); return { id: `${file.name}-${i}`, month: monthFrom(pick(x, ["month", "period"]), file.name), operator: text(pick(x, ["operator name", "operator", "airline"])), continent: text(pick(x, ["operator continent", "continent", "region"])), country: text(pick(x, ["operator country", "country"])), engineModel: text(model), engineType: typeFrom(model), family: familyFrom(model), dash: dashFrom(model), status: statusFrom(pick(x, ["status", "engine status"])), engines: num(pick(x, ["number of engines", "engines", "engine count", "count"])) || 1 }; }); }

function SectionTitle({ title, subtitle }) {
  return (
    <div style={{ marginBottom: 12 }}>
      <h2 style={{ margin: 0, fontSize: 20 }}>{title}</h2>
      <p style={{ margin: "4px 0 0", color: "#94a3b8", fontSize: 13 }}>{subtitle}</p>
    </div>
  );
}

export default function App() {
  const folderRef = useRef(null);
  const [rows, setRows] = useState([]);
  const [trendRows, setTrendRows] = useState([]);
  const [activeTab, setActiveTab] = useState("overview");
  const [singleFileName, setSingleFileName] = useState("");
  const [folderInfo, setFolderInfo] = useState({ count: 0, months: [] });
  const [loadingSingle, setLoadingSingle] = useState(false);
  const [loadingFolder, setLoadingFolder] = useState(false);
  const [expanded, setExpanded] = useState({});
  const [error, setError] = useState("");
  const [filters, setFilters] = useState({ family: "All", continent: "All", status: "All", dash: "All", country: "All", operator: "All" });

  const baseRows = useMemo(() => rows.filter((r) => (filters.family === "All" || r.family === filters.family) && (filters.continent === "All" || r.continent === filters.continent) && (filters.status === "All" || r.status === filters.status) && (filters.dash === "All" || r.dash === filters.dash)), [rows, filters]);
  const countryOptions = useMemo(() => ["All", ...Array.from(new Set(baseRows.map((r) => r.country))).sort()], [baseRows]);
  const operatorOptions = useMemo(() => ["All", ...Array.from(new Set(baseRows.filter((r) => filters.country === "All" || r.country === filters.country).map((r) => r.operator))).sort()], [baseRows, filters.country]);
  const filtered = useMemo(() => baseRows.filter((r) => (filters.country === "All" || r.country === filters.country) && (filters.operator === "All" || r.operator === filters.operator)), [baseRows, filters.country, filters.operator]);
  const options = useMemo(() => { const get = (k) => ["All", ...Array.from(new Set(rows.map((r) => r[k]))).sort()]; return { family: get("family"), continent: get("continent"), status: get("status"), dash: get("dash") }; }, [rows]);

  const grouped = useMemo(() => { const map = new Map(); filtered.forEach((r) => { const key = `${r.operator}||${r.country}||${r.continent}`; if (!map.has(key)) map.set(key, { key, operator: r.operator, country: r.country, continent: r.continent, family: {}, dash: {}, status: {}, engines: 0 }); const g = map.get(key); g.family[r.family] = (g.family[r.family] || 0) + r.engines; g.dash[r.dash] = (g.dash[r.dash] || 0) + r.engines; g.status[r.status] = (g.status[r.status] || 0) + r.engines; g.engines += r.engines; }); return Array.from(map.values()).sort((a, b) => b.engines - a.engines); }, [filtered]);
  const kpi = useMemo(() => ({ total: filtered.reduce((s, r) => s + r.engines, 0), active: filtered.filter((r) => r.status === "Active").reduce((s, r) => s + r.engines, 0), activeCFM: filtered.filter((r) => r.status === "Active" && r.engineType === "CFM").reduce((s, r) => s + r.engines, 0), activeLEAP: filtered.filter((r) => r.status === "Active" && r.engineType === "LEAP").reduce((s, r) => s + r.engines, 0) }), [filtered]);
  const operatorRanking = useMemo(() => grouped.slice(0, 12).map((o) => ({ name: o.operator, engines: o.engines })), [grouped]);
  const byContinent = useMemo(() => Object.entries(filtered.reduce((m, r) => ((m[r.continent] = (m[r.continent] || 0) + r.engines), m), {})).map(([name, engines]) => ({ name, engines })).sort((a, b) => b.engines - a.engines), [filtered]);
  const byCountry = useMemo(() => Object.entries(filtered.reduce((m, r) => ((m[r.country] = (m[r.country] || 0) + r.engines), m), {})).map(([name, engines]) => ({ name, engines })).sort((a, b) => b.engines - a.engines), [filtered]);
  const byFamily = useMemo(() => Object.entries(filtered.reduce((m, r) => ((m[r.family] = (m[r.family] || 0) + r.engines), m), {})).map(([name, value]) => ({ name, value })), [filtered]);
  const byDash = useMemo(() => Object.entries(filtered.reduce((m, r) => ((m[r.dash] = (m[r.dash] || 0) + r.engines), m), {})).map(([dash, engines]) => ({ dash, engines })), [filtered]);
  const byType = useMemo(() => Object.entries(filtered.reduce((m, r) => ((m[r.engineType] = (m[r.engineType] || 0) + r.engines), m), {})).map(([name, value]) => ({ name, value })), [filtered]);
  const byStatus = useMemo(() => Object.entries(filtered.reduce((m, r) => ((m[r.status] = (m[r.status] || 0) + r.engines), m), {})).map(([status, value]) => ({ status, value })), [filtered]);
  const opportunity = useMemo(() => Object.entries(filtered.reduce((m, r) => ((["Stored", "Maintenance", "Repair"].includes(r.status) ? (m[r.operator] = (m[r.operator] || 0) + r.engines) : null), m), {})).map(([operator, value]) => ({ operator, value })).sort((a, b) => b.value - a.value).slice(0, 12), [filtered]);
  const trendByMonth = useMemo(() => { const m = {}; trendRows.forEach((r) => { if (!m[r.month]) m[r.month] = { month: r.month, LEAP: 0, CFM: 0 }; m[r.month][r.engineType] += r.engines; }); return Object.values(m).sort((a, b) => monthSort(a.month) - monthSort(b.month)); }, [trendRows]);
  const leapGrowth = useMemo(() => { if (trendByMonth.length < 2) return 0; const p = trendByMonth[trendByMonth.length - 2].LEAP; const c = trendByMonth[trendByMonth.length - 1].LEAP; return p ? ((c - p) / p) * 100 : c ? 100 : 0; }, [trendByMonth]);
  const leapRegion = useMemo(() => { const months = Array.from(new Set(trendRows.map((r) => r.month))).sort((a, b) => monthSort(a) - monthSort(b)); const continents = Array.from(new Set(trendRows.map((r) => r.continent))); return months.map((m) => { const row = { month: m }; continents.forEach((c) => { row[c] = trendRows.filter((r) => r.month === m && r.continent === c && r.engineType === "LEAP").reduce((s, r) => s + r.engines, 0); }); return row; }); }, [trendRows]);

  async function parseFiles(fileList) { const files = Array.from(fileList || []).filter((f) => /\.(xlsx|xls)$/i.test(f.name)); if (!files.length) throw new Error("No Excel files found."); const out = []; for (const file of files) { const data = await file.arrayBuffer(); out.push(...parseWorkbook(file, XLSX.read(data, { type: "array" }))); } return { files, rows: out }; }
  async function onSingle(e) { setError(""); setLoadingSingle(true); try { const file = e.target.files?.[0]; if (!file) return; const result = await parseFiles([file]); setRows(result.rows); setSingleFileName(file.name); setActiveTab("overview"); setFilters({ family: "All", continent: "All", status: "All", dash: "All", country: "All", operator: "All" }); } catch (err) { setError(err.message || "Failed to parse file."); } finally { setLoadingSingle(false); } }
  async function onFolder(e) { setError(""); setLoadingFolder(true); try { const result = await parseFiles(e.target.files); const months = Array.from(new Set(result.rows.map((r) => r.month))).sort((a, b) => monthSort(a) - monthSort(b)); setTrendRows(result.rows); setFolderInfo({ count: result.files.length, months }); setActiveTab("forecast"); } catch (err) { setError(err.message || "Failed to parse folder files."); } finally { setLoadingFolder(false); } }

  return <div style={{ minHeight: "100vh", fontFamily: "Inter, Segoe UI, sans-serif", background: "radial-gradient(circle at 0% 0%, #1e293b 0%, #0f172a 35%, #020617 100%)", color: "#e2e8f0" }}><div style={{ maxWidth: 1500, margin: "0 auto", padding: 24 }}>
    <div style={{ ...card(18), marginBottom: 16 }}><h1 style={{ margin: 0, fontSize: 28 }}>Aerospace Engine Lifecycle Dashboard</h1><p style={{ margin: "8px 0 0", color: "#94a3b8" }}>Dual mode: single file analysis + multi-file LEAP forecast.</p></div>
    <div style={{ ...card(16), marginBottom: 16, display: "grid", gap: 14, gridTemplateColumns: "repeat(auto-fit,minmax(280px,1fr))" }}>
      <div><h3>Upload & Analyze (Single Month)</h3><input type="file" accept=".xlsx,.xls" onChange={onSingle} /><div style={{ marginTop: 8, color: "#94a3b8" }}>{loadingSingle ? "Parsing..." : singleFileName ? `Loaded: ${singleFileName}` : "No file loaded"}</div></div>
      <div><h3>LEAP Demand Analysis (Multi-Month)</h3><input ref={folderRef} type="file" multiple onClick={() => { if (folderRef.current) { folderRef.current.setAttribute("webkitdirectory", ""); folderRef.current.setAttribute("directory", ""); } }} onChange={onFolder} accept=".xlsx,.xls" /><div style={{ marginTop: 8, color: "#94a3b8" }}>{loadingFolder ? "Reading files..." : folderInfo.count ? `${folderInfo.count} files | Months: ${folderInfo.months.join(", ")}` : "No folder analyzed"}</div></div>
    </div>
    {error ? <div style={{ ...card(14), borderColor: "rgba(248,113,113,0.45)", color: "#fda4af", marginBottom: 14 }}>{error}</div> : null}
    {rows.length ? <div style={{ ...card(14), marginBottom: 14, display: "grid", gap: 10, gridTemplateColumns: "repeat(auto-fit,minmax(180px,1fr))" }}>
      {[
        ["Engine Family", "family", options.family],
        ["Operator Continent", "continent", options.continent],
        ["Status", "status", options.status],
        ["Dash", "dash", options.dash],
        ["Operator Country", "country", countryOptions],
        ["Operator Name", "operator", operatorOptions],
      ].map(([label, key, list]) => <div key={key}><div style={{ fontSize: 12, color: "#94a3b8", marginBottom: 6 }}>{label}</div><select value={filters[key]} onChange={(e) => setFilters((prev) => { const next = { ...prev, [key]: e.target.value }; if (["family", "continent", "status", "dash"].includes(key)) { next.country = "All"; next.operator = "All"; } if (key === "country") next.operator = "All"; return next; })} style={{ width: "100%", borderRadius: 10, border: "1px solid rgba(148,163,184,0.3)", background: "rgba(15,23,42,0.7)", color: "#e2e8f0", height: 36, padding: "0 8px" }}>{list.map((opt) => <option key={opt} value={opt}>{opt}</option>)}</select></div>)}
    </div> : null}
    <div style={{ display: "flex", gap: 10, flexWrap: "wrap", marginBottom: 16 }}>{[["overview", "Operator Overview"],["geo", "Geographic Intelligence"],["portfolio", "Engine Portfolio"],["lifecycle", "Status Lifecycle"],["forecast", "LEAP Forecast"]].map(([id, label]) => <button key={id} onClick={() => setActiveTab(id)} style={{ border: "1px solid rgba(148,163,184,0.25)", background: activeTab === id ? "rgba(56,189,248,0.2)" : "rgba(15,23,42,0.55)", color: "#e2e8f0", borderRadius: 999, padding: "8px 14px", cursor: "pointer" }}>{label}</button>)}</div>
    {activeTab !== "forecast" && !rows.length ? <div style={{ ...card(16), color: "#94a3b8" }}>Upload a single file to view analytics tabs.</div> : null}
    {activeTab === "overview" && rows.length ? <div style={{ display: "grid", gap: 16 }}>
      <div style={{ display: "grid", gap: 12, gridTemplateColumns: "repeat(auto-fit,minmax(180px,1fr))" }}>{[["Total Engines", kpi.total, "#38bdf8"], ["Active Engines", kpi.active, "#34d399"], ["Active CFM", kpi.activeCFM, "#60a5fa"], ["Active LEAP", kpi.activeLEAP, "#f97316"]].map(([l, v, c]) => <div key={l} style={{ ...card(14), borderColor: `${c}55` }}><div style={{ color: "#94a3b8" }}>{l}</div><div style={{ fontSize: 30, fontWeight: 700, color: c }}>{fmt(v)}</div></div>)}</div>
      <div style={{ ...card(14), overflowX: "auto" }}><SectionTitle title="Operator Engine Distribution" subtitle="Grouped rows with expandable status breakdown" /><table style={{ width: "100%", borderCollapse: "collapse", fontSize: 13 }}><thead><tr style={{ color: "#94a3b8", textAlign: "left" }}><th style={{ padding: 8 }} /><th style={{ padding: 8 }}>Country</th><th style={{ padding: 8 }}>Operator</th><th style={{ padding: 8 }}>Continent</th><th style={{ padding: 8 }}>Family</th><th style={{ padding: 8 }}>Dash</th><th style={{ padding: 8 }}>Status</th><th style={{ padding: 8 }}>Engines</th></tr></thead><tbody>{grouped.slice(0, 40).map((r) => <><tr key={r.key} style={{ borderTop: "1px solid rgba(148,163,184,0.16)" }}><td style={{ padding: 8 }}><button onClick={() => setExpanded((p) => ({ ...p, [r.key]: !p[r.key] }))}>{expanded[r.key] ? "-" : "+"}</button></td><td style={{ padding: 8 }}>{r.country}</td><td style={{ padding: 8 }}>{r.operator}</td><td style={{ padding: 8 }}>{r.continent}</td><td style={{ padding: 8 }}>{Object.keys(r.family).slice(0,2).join(", ") || "Mixed"}</td><td style={{ padding: 8 }}>{Object.keys(r.dash).slice(0,3).join(", ") || "Mixed"}</td><td style={{ padding: 8 }}>{Object.entries(r.status).map(([k,v]) => `${k}: ${fmt(v)}`).join(" | ")}</td><td style={{ padding: 8 }}>{fmt(r.engines)}</td></tr>{expanded[r.key] ? <tr><td colSpan={8} style={{ padding: 12, background: "rgba(15,23,42,0.45)" }}>Status Breakdown: {Object.entries(r.status).map(([k,v]) => `${k} (${fmt(v)})`).join(" | ")}</td></tr> : null}</>)}</tbody></table></div>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(360px,1fr))", gap: 16 }}><div style={{ ...card(14), minHeight: 340 }}><SectionTitle title="Operator Ranking" subtitle="Top operators by engine count" /><ResponsiveContainer width="100%" height={270}><BarChart data={operatorRanking}><CartesianGrid strokeDasharray="3 3" stroke="rgba(148,163,184,0.2)" /><XAxis dataKey="name" hide /><YAxis /><Tooltip /><Bar dataKey="engines" fill="#38bdf8" radius={[6,6,0,0]} /></BarChart></ResponsiveContainer></div><div style={{ ...card(14), minHeight: 340 }}><SectionTitle title="Status Breakdown" subtitle="Lifecycle mix" /><ResponsiveContainer width="100%" height={270}><PieChart><Pie data={byStatus} dataKey="value" nameKey="status" outerRadius={95} label>{byStatus.map((x) => <Cell key={x.status} fill={STATUS_COLORS[x.status] || STATUS_COLORS.Unknown} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></div></div>
    </div> : null}
    {activeTab === "geo" && rows.length ? <div style={{ display: "grid", gap: 16, gridTemplateColumns: "repeat(auto-fit,minmax(320px,1fr))" }}><div style={{ ...card(14), minHeight: 320 }}><SectionTitle title="Continent Breakdown" subtitle="Engines per continent" /><ResponsiveContainer width="100%" height={240}><BarChart data={byContinent}><CartesianGrid strokeDasharray="3 3" stroke="rgba(148,163,184,0.2)" /><XAxis dataKey="name" /><YAxis /><Tooltip /><Bar dataKey="engines" fill="#34d399" /></BarChart></ResponsiveContainer></div><div style={{ ...card(14), minHeight: 320 }}><SectionTitle title="Country Drilldown" subtitle="Top countries" /><ResponsiveContainer width="100%" height={240}><BarChart data={byCountry.slice(0,12)}><CartesianGrid strokeDasharray="3 3" stroke="rgba(148,163,184,0.2)" /><XAxis dataKey="name" hide /><YAxis /><Tooltip /><Bar dataKey="engines" fill="#a78bfa" /></BarChart></ResponsiveContainer></div></div> : null}
    {activeTab === "portfolio" && rows.length ? <div style={{ display: "grid", gap: 16, gridTemplateColumns: "repeat(auto-fit,minmax(320px,1fr))" }}><div style={{ ...card(14), minHeight: 330 }}><SectionTitle title="Family Distribution" subtitle="CFM56 / LEAP families" /><ResponsiveContainer width="100%" height={250}><PieChart><Pie data={byFamily} dataKey="value" nameKey="name" outerRadius={90} label>{byFamily.map((x, i) => <Cell key={x.name} fill={PIE_COLORS[i % PIE_COLORS.length]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></div><div style={{ ...card(14), minHeight: 330 }}><SectionTitle title="Dash Analysis" subtitle="Most used dash" /><ResponsiveContainer width="100%" height={250}><BarChart data={byDash}><CartesianGrid strokeDasharray="3 3" stroke="rgba(148,163,184,0.2)" /><XAxis dataKey="dash" /><YAxis /><Tooltip /><Bar dataKey="engines" fill="#f97316" /></BarChart></ResponsiveContainer></div><div style={{ ...card(14), minHeight: 330 }}><SectionTitle title="Engine Type Split" subtitle="CFM vs LEAP" /><ResponsiveContainer width="100%" height={250}><PieChart><Pie data={byType} dataKey="value" nameKey="name" outerRadius={90} label>{byType.map((x) => <Cell key={x.name} fill={ENGINE_TYPE_COLORS[x.name] || "#94a3b8"} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></div></div> : null}
    {activeTab === "lifecycle" && rows.length ? <div style={{ display: "grid", gap: 16, gridTemplateColumns: "repeat(auto-fit,minmax(320px,1fr))" }}><div style={{ ...card(14), minHeight: 330 }}><SectionTitle title="Status Breakdown" subtitle="Active vs stored vs repair" /><ResponsiveContainer width="100%" height={250}><PieChart><Pie data={byStatus} dataKey="value" nameKey="status" outerRadius={90} label>{byStatus.map((x) => <Cell key={x.status} fill={STATUS_COLORS[x.status] || STATUS_COLORS.Unknown} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></div><div style={{ ...card(14), minHeight: 330 }}><SectionTitle title="Opportunity Score" subtitle="Stored + Maintenance + Repair" /><ResponsiveContainer width="100%" height={250}><BarChart data={opportunity}><CartesianGrid strokeDasharray="3 3" stroke="rgba(148,163,184,0.2)" /><XAxis dataKey="operator" hide /><YAxis /><Tooltip /><Bar dataKey="value" fill="#f59e0b" /></BarChart></ResponsiveContainer></div></div> : null}
    {activeTab === "forecast" ? (trendRows.length ? <div style={{ display: "grid", gap: 16 }}><div style={{ display: "grid", gap: 12, gridTemplateColumns: "repeat(auto-fit,minmax(220px,1fr))" }}><div style={{ ...card(14), borderColor: "rgba(249,115,22,0.45)" }}><div style={{ color: "#94a3b8" }}>LEAP MoM Growth</div><div style={{ fontSize: 32, color: leapGrowth >= 0 ? "#34d399" : "#f87171", fontWeight: 700 }}>{leapGrowth >= 0 ? "+" : ""}{leapGrowth.toFixed(1)}%</div></div><div style={{ ...card(14) }}><div style={{ color: "#94a3b8" }}>Months</div><div style={{ fontSize: 24, fontWeight: 700 }}>{folderInfo.months.join(", ")}</div></div><div style={{ ...card(14) }}><div style={{ color: "#94a3b8" }}>Files Processed</div><div style={{ fontSize: 32, fontWeight: 700 }}>{folderInfo.count}</div></div></div><div style={{ display: "grid", gap: 16, gridTemplateColumns: "repeat(auto-fit,minmax(360px,1fr))" }}><div style={{ ...card(14), minHeight: 330 }}><SectionTitle title="Monthly LEAP Trend" subtitle="LEAP by month" /><ResponsiveContainer width="100%" height={250}><LineChart data={trendByMonth}><CartesianGrid strokeDasharray="3 3" stroke="rgba(148,163,184,0.2)" /><XAxis dataKey="month" /><YAxis /><Tooltip /><Line type="monotone" dataKey="LEAP" stroke="#f97316" strokeWidth={3} /></LineChart></ResponsiveContainer></div><div style={{ ...card(14), minHeight: 330 }}><SectionTitle title="CFM vs LEAP Growth" subtitle="Two-line trend" /><ResponsiveContainer width="100%" height={250}><LineChart data={trendByMonth}><CartesianGrid strokeDasharray="3 3" stroke="rgba(148,163,184,0.2)" /><XAxis dataKey="month" /><YAxis /><Tooltip /><Legend /><Line type="monotone" dataKey="CFM" stroke="#38bdf8" strokeWidth={2.5} /><Line type="monotone" dataKey="LEAP" stroke="#f97316" strokeWidth={2.5} /></LineChart></ResponsiveContainer></div></div><div style={{ ...card(14), minHeight: 350 }}><SectionTitle title="Region-wise LEAP Growth" subtitle="Continent adoption" /><ResponsiveContainer width="100%" height={270}><LineChart data={leapRegion}><CartesianGrid strokeDasharray="3 3" stroke="rgba(148,163,184,0.2)" /><XAxis dataKey="month" /><YAxis /><Tooltip /><Legend />{Object.keys(leapRegion[0] || {}).filter((k) => k !== "month").map((c, i) => <Line key={c} type="monotone" dataKey={c} stroke={PIE_COLORS[i % PIE_COLORS.length]} strokeWidth={2} />)}</LineChart></ResponsiveContainer></div></div> : <div style={{ ...card(16), color: "#94a3b8" }}>Upload multiple monthly files to view LEAP forecast.</div>) : null}
  </div></div>;
}